
name: Test project
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: make install
      - run: make build
      - run: make publish
      - run: make package-install
      - run: make lint
